In [2]:
# Declaring path variables to make Basemap work in jupyter hub. Make sure that the conda environment path matches yours
import os
os.environ['PATH'] = '/home/jovyan/my-conda-envs/qiime2-2019.1/bin:' + os.environ['PATH']
os.environ['PROJ_LIB'] = '/home/jovyan/my-conda-envs/qiime2-2019.1/share/proj'

# General Tool Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from mpl_toolkits.basemap import Basemap
import biota
import biota.plot as bpl
import collections
import matplotlib.patches as patches
from matplotlib.patches import Rectangle
import math
import pickle 

import lasio



%matplotlib inline

In [3]:
df = pd.read_csv('PI Data.csv')

In [5]:
#Save datafram df as pickle
df.to_pickle("SamplePickel.pkl")

In [7]:
#Save datafram df as pickle
df.to_pickle("SamplePickel.pkl")
#Define Pickle file path
filepath = ('SamplePickel.pkl')
#Set read write permissions on pickle file
file = open(filepath,'rb')
#load pickle into newdf
newdf = pickle.load(file)

,Unnamed: 0,WELL NAME,STAGE,Start Time,End Time,Event Duration,ACTUAL DURATION,ACTUAL PROPPANT TOTAL,ACTUAL PUMP TIME,API,...,PROPPANT 2,PROPPANT 2|DESIGN,PROPPANT 2|PUMPED,SHOTS PER STAGE,TOTAL CLEAN VOLUME,SHOTS ACTUAL,SHOTS PLANNED,CLUSTERS,Formation,Pad
0,0,MOSASAURUS 4-16N-9W 11H,2,2018-02-20 21:15:39,2018-02-20 22:45:24,1900-01-01 11:54:00,1.495833,326970,1.495833,3507325703,...,PROPPANT - UNTREATED|WHITE|40/70,163800.0,163800,24.0,6200.0,24,24.0,5,MRMC 400,MOSASAURUS
1,1,MOSASAURUS 4-16N-9W 11H,3,2018-02-21 01:24:19,2018-02-21 02:45:17,1900-01-01 08:23:12,1.349444,326970,1.349444,3507325703,...,PROPPANT - UNTREATED|WHITE|40/70,163800.0,163800,24.0,5617.0,24,24.0,5,MRMC 400,MOSASAURUS
2,2,MOSASAURUS 4-16N-9W 11H,4,2018-02-21 05:13:23,2018-02-21 06:42:57,1900-01-01 11:49:36,1.492778,326970,1.492778,3507325703,...,PROPPANT - UNTREATED|WHITE|40/70,163800.0,163800,24.0,6282.0,24,24.0,5,MRMC 400,MOSASAURUS
3,3,MOSASAURUS 4-16N-9W 11H,5,2018-02-23 18:23:24,2018-02-23 19:38:09,1900-01-01 05:54:00,1.245833,327060,1.245833,3507325703,...,PROPPANT - UNTREATED|WHITE|40/70,163800.0,163860,24.0,5255.0,24,24.0,5,MRMC 400,MOSASAURUS
4,4,MOSASAURUS 4-16N-9W 11H,6,2018-02-23 23:43:17,2018-02-24 01:01:01,1900-01-01 07:05:36,1.295556,326970,1.295556,3507325703,...,PROPPANT - UNTREATED|WHITE|40/70,163800.0,163800,24.0,5469.0,24,24.0,5,MRMC 400,MOSASAURUS